# Copyright 2022 Google LLC

apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: cicd-multiapp-platinum
requires:
    # most interesting are Accounts and Ledger
  - configs: [app01]
    path: apps/app01/skaffold.yaml
  - configs: [app02]
    path: apps/app02/skaffold.yaml
  - configs: [app03]
    path: apps/app03/skaffold.yaml
