# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Service 'store-green9' has 9x capacity than store-v1. We simulate it with 9x pods ands 9x capacity (max-rate-per-endpoint)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-green9
spec:
  replicas: 9
  selector:
    matchLabels:
      app: store-bluegreen
      version: v2
  template:
    metadata:
      labels:
        app: store-bluegreen
        version: v2
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.1
        ports:
          - containerPort: 8080
        env:
        - name: METADATA
          value: "store-green9"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: store-green9
#   annotations:
#     networking.gke.io/max-rate-per-endpoint: "90"
#     cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "store-green9-neg"}}}'
# spec:
#   selector:
#     app: store-bluegreen
#     version: v2
#   ports:
#   - port: 8080
#     targetPort: 8080