apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#setting-cross-cutting-fields
#namespace: my-namespace
#nameSuffix: "-prod"
commonLabels:
  is-app-in-production: bingo
  ricc-awesome-selector: canary-or-prod
labels:
  - pairs: 
      ricc-env: prod
    includeSelectors: false
commonAnnotations:
  oncallPager: 800-555-1234 (for Production outages only)
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my PROD manifests.
# resources:
# - deployment.yaml
components:
  - ../base


# This only worked with ruby!

# apiVersion: kustomize.config.k8s.io/v1alpha1
# kind: Component
# replicas:
#   - name: ricc-ruby
#     count: 11
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: COMMON_CLOUD_DEPLOY_TARGET
        value: "04 CProd - COMMON Production"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CLOUD_DEPLOY_TARGET_SHORT_COMMON
        value: "prod"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR_COMMON
        value: white # prod is WHITE :)
  target:
    kind: Deployment
# for both:
#  name: app01-kupython
#  name: app02-kuruby
