# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# HurricaneAlex: remove Deployments and leave only Services
apiVersion: v1
kind: Service
metadata:
  name: __APPNAME__-sol2-svc-prod # was: svc-prod90 # former svc2-prod90
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": ""}}}'
# Name NEEDS to be autodetected because it needs to be different per cluster.
#    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "__APPNAME__-sol2-svc-prod-neg"}}}'
spec:
  selector:
    app: __K8S_APP_SELECTOR__
    # I get ZERO so lets try to make selector laxer
    ricc-env: prod
  ports:
  - port: 8080
    targetPort: 8080
