apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -canary
resources:
  - ../../base
components:
  - ../../../../../components/common/canary
replicas:
  - name: app03-kunode
    count: 1
