# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: app01-kupython # was 'web' and it worked
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: app01-kupython # was 'web' and it worked
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-kupython # was 'web' and it worked
spec:
  selector:
    matchLabels:
      app: app01-kupython # was 'web' and it worked
  template:
    metadata:
      labels:
        app: app01-kupython # was 'web' and it worked
    spec:
      containers:
      - name: app01-kupython # was 'web' and it worked
        image: skaf-app01-python-buildpacks # used to be: 'skaffold-buildpacks'
        env:
          - name: PORT
            value: "8080"
          - name: RICCARDO_MESSAGE # TEST_RICCARDO. Ruby has RICCARDO_MESSAGE and uses it, so changing in case I want to refactor in common :)
            value: |
              I copied and pasted web.yaml inside base and now Im trying to use kustomize instead.
              Not sure if Ill survive but we'll see.
              Why am I using Kustomize? Thanks for asking. Two reasons mainly:
              1. Learn kustomize
              2. the only legitimate reason is to DRY the 4 dev/stagingca/ary/prod while injecting
                 a slight difference in Canary vs Prod config (9 vs 1 Replicas respectively)

              2022-07-19 BUG: Cloud Deploy seems stuck to version 2.14
          - name: FAVORITE_COLOR
            value: fbf4e2 # NACRE / madreperla
          # - name: USE_KUSTOMIZE
          #   value: "true"
          - name: APP_CODE
            value: app01-kustomize
          - name: APP_NAME
            value: A Wonderful App in Python (app01)
        ports:
          - containerPort: 8080
