# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: app03-kunode
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: app03-kunode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03-kunode
spec:
  selector:
    matchLabels:
      app: app03-kunode
  template:
    metadata:
      labels:
        app: app03-kunode
    spec:
      containers:
      - name: app03-kunode
        image: aablsk-app03-kunode-skaffold    # Dockerized
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: A Wonderful App in NodeJS (app03)
        - name: RICCARDO_MESSAGE
          value: |
            Hi! This is NOT Riccardo 😱🙀😳
        - name: FAVORITE_COLOR
          value: pink # default bkg color, will make it white in prod and yellow in canary.
