apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../components/common/staging
replicas:
  - name: app03-kunode
    count: 1
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CLOUD_DEPLOY_TARGET
        value: "02 Staging (pls read with French accent)"
  target:
    kind: Deployment
    name: app03-kuruby
