# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
#nameSuffix: "-stag"
commonLabels:
  ricc-awesome-selector: dev-or-staging # nothing serious
  ricc-env: staging
commonAnnotations:
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my STAGING manifests.
    Removed the -staging suffix as it added additional unnecessary complexity.
components:
  - ../base
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: COMMON_CLOUD_DEPLOY_TARGET
        value: "02 CStaging - COMMON Staging"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CLOUD_DEPLOY_TARGET_SHORT_COMMON
        value: "staging"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR_COMMON
        value: cyan
  target:
    kind: Deployment
