apiVersion: v1
kind: Service
metadata:
  name: app02-kuruby # as in App02, ruby and Kustomized
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: app02-kuruby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-kuruby
spec:
  selector:
    matchLabels:
      app: app02-kuruby
  template:
    metadata:
      labels:
        app: app02-kuruby
    spec:
      containers:
      - name: app02-kuruby
        image: ricc-app02-kuruby-skaffold    # Dockerized
        ports:
        - containerPort: 8080 # it MUST be 9292 since puma uses this by DFLT. Note on ContainerPort: My pod expects traffic here.
        env:
        - name: RACK_ENV # https://docs.pivotal.io/application-service/2-7/buildpacks/ruby/ruby-tips.html
          value: "development" # todo consider updating to DEPLOYMENT :) https://www.hezmatt.org/~mpalmer/blog/2013/10/13/rack_env-its-not-for-you.html
        - name: APP_NAME
          value: A Wonderful App in Ruby (app02)
        - name: RICCARDO_MESSAGE
          value: |
            Hi! This is the default message if you dont customize to come to another
            target (dev, prod, ..). This was fixed in v1.16 with port mismatch.
            I'm still trying to bake the CD target into this which kustomize should add in
            overlays but nisba: ENV['RICCARDO_KUSTOMIZE_ENV'] seems null.
            Btw moved 9292 to 8080 since I need
        - name: FAVORITE_COLOR
          value: pink # default bkg color, will make it white in prod and yellow in canary.

